### ISSUE TITLE
how to organize  font's number of css while using Google Font online?

### ISSUE THREAD

**Issue by yinsang** [black7375/font-range#9]
```
const {fontRange} = require('font-range')
fontRange('https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap', './NotoSansSC-Regular.otf');

```
![image](https://user-images.githubusercontent.com/12373328/190996405-7c566720-ce30-4188-bea9-c9074bb3f217.png)
Online  xxx.css  start at 4, not 0.
But font range generate sub.woff2 start at 0, not 4.
![image](https://user-images.githubusercontent.com/12373328/190996565-17f1c1a7-80db-497e-919e-71d654621e1c.png). 
NotoSansKR starts at 0, but NotoSan Simple Chinese starts at 4.
Perfer:
Generate the css file which it's font path is local sub font.
```

@font-face {
  font-family: 'Noto Sans SC';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("./NotoSansSC-Regular_0.woff2") format('woff2');
  unicode-range: U+1f1e9-1f1f5, U+1f1f7-1f1ff, U+1f21a, U+1f232, U+1f234-1f237, U+1f250-1f251, U+1f300, U+1f302-1f308, U+1f30a-1f311, U+1f315, U+1f319-1f320, U+1f324, U+1f327, U+1f32a, U+1f32c-1f32d, U+1f330-1f357, U+1f359-1f37e;
}
```

**Comment by black7375** [comment]
That sounds like a good suggestion.
It will not be applied right now, but I will consider it in the future update.

**Comment by yinsang** [comment]
Thanks

**Comment by black7375** [comment]
Try to `v1.0.0`
https://github.com/black7375/font-range#font-range-1

**Comment by yinsang** [comment]
> Try to `v1.0.0` https://github.com/black7375/font-range#font-range-1

Thank you so much. I tried and it worked perfectly.
